import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

type Language = "zh" | "en";
type TranslationParams = Record<string, string | number>;

const STORAGE_KEY = "chileoma-language";

const translations: Record<Language, Record<string, string>> = {
  zh: {
    "nav.community": "社区",
    "nav.rankings": "排行榜",
    "nav.aiChat": "AI聊天",
    "nav.profile": "我的",
    "nav.discussion": "交流",
    "nav.restaurants": "餐厅",
    "nav.admin": "管理后台",
    "language.label": "语言",
    "language.switch": "切换语言",

    "common.back": "返回",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.edit": "编辑",
    "common.delete": "删除",
    "common.loading": "加载中",
    "common.view": "查看",
    "common.viewDetails": "查看详情",
    "common.submit": "提交",
    "common.user": "用户",
    "common.justNow": "刚刚",
    "common.noRating": "暂无评分",
    "common.rating": "评分",
    "common.reviews": "{count} 条评分",
    "common.score": "综合分",
    "common.perPerson": "人均：",
    "common.aboutKm": "约 {distance} km",
    "common.unclassified": "未分类",
    "common.aiRecommend": "AI 推荐",
    "common.aiAsk": "AI 问问这家店",

    "home.login": "登录",
    "home.register": "注册",
    "home.startNow": "立即开始",
    "home.learnMore": "了解更多",
    "home.heroTitle": "吃了吗？",
    "home.heroSubtitle": "发现美食，分享快乐。与朋友一起探索城市最好的餐厅，分享你的美食故事。",
    "home.loginTipTitle": "登录提示",
    "home.loginTipBody": "请使用 Google、Microsoft、Facebook 或 Apple 账号登录。跳转后请直接点击对应的第三方登录按钮，无需输入邮箱。",
    "home.featureShareTitle": "分享美食",
    "home.featureShareBody": "发布你的美食照片和评价，与社区分享你的发现。",
    "home.featureAiTitle": "AI推荐",
    "home.featureAiBody": "告诉AI你的口味偏好，获得智能推荐的餐厅。",
    "home.featureRankTitle": "发现排行榜",
    "home.featureRankBody": "浏览你所在地区最受欢迎的餐厅排行榜。",
    "home.ctaTitle": "准备好了吗？",
    "home.ctaBody": "加入吃了吗社区，发现美食，分享快乐，与美食爱好者一起探索城市的每一个角落。",
    "home.registerNow": "现在注册",
    "home.footer": "© 2024 吃了吗 - 美食分享与餐厅推荐平台",
    "home.errorInvalidEmail": "注册失败：只允许使用 @student.xjtlu.edu.cn 邮箱地址注册。请使用你的大学邮箱或第三方账号（Google、Microsoft等）重新登录。",
    "home.errorOauthFailed": "登录失败：认证出错，请稍后重试。",

    "feed.badge": "社区",
    "feed.title": "交流",
    "feed.subtitle": "分享吃饭体验、找同学推荐、记录你发现的好店。",
    "feed.publish": "发布帖子",
    "feed.loadMore": "加载更多",
    "feed.empty": "暂无帖子",
    "feed.publishFirst": "发布第一条帖子",
    "feed.badImage": "这条旧帖的原始图片地址已经失效，已隐藏坏图。",
    "feed.deleteTitle": "删除帖子",
    "feed.confirmDelete": "确定要删除这条帖子吗？",
    "feed.toastLikeFailed": "点赞失败：{message}",
    "feed.toastUnlikeFailed": "取消点赞失败：{message}",
    "feed.toastDeleted": "帖子已删除",
    "feed.toastNoDeletePermission": "你没有权限删除这条帖子",
    "feed.toastNotFound": "帖子不存在",
    "feed.toastDeleteFailed": "删除失败：{message}",

    "publish.back": "返回社区",
    "publish.title": "分享你的美食故事",
    "publish.titleLabel": "标题 *",
    "publish.titleHelp": "（如：某餐厅的招牌菜真绝了）",
    "publish.titlePlaceholder": "例如：XXX餐厅的招牌菜、这家店的环境超舒服...",
    "publish.contentLabel": "内容 *",
    "publish.contentHelp": "（分享你的美食体验和感受）",
    "publish.contentPlaceholder": "例如：这家店的菜品很新鲜，特别推荐他们的...\n环境很舒适，适合和朋友聚餐...\n价格也很合理，性价比很高...",
    "publish.chars": "{count}/{max} 字符",
    "publish.ratingOptional": "评分（可选）",
    "publish.uploadImages": "上传图片（最多9张）",
    "publish.uploadCta": "点击或拖拽上传图片",
    "publish.uploadSupport": "支持 JPG、PNG、WebP 格式",
    "publish.submitting": "发布中...",
    "publish.submit": "发布",
    "publish.tipsTitle": "分享小贴士",
    "publish.tipPhotos": "清晰的图片能让你的分享更吸引人",
    "publish.tipDetails": "详细的描述帮助其他用户更好地了解",
    "publish.tipRating": "给餐厅评分，帮助社区了解质量",
    "publish.tipRules": "遵守社区规则，不发布不当内容",
    "publish.toastSuccess": "发布成功！",
    "publish.toastFailed": "发布失败：{message}",
    "publish.toastRequired": "请填写标题和内容",

    "restaurants.title": "发现餐厅",
    "restaurants.subtitle": "可以按关键词搜索，也可以定位查看 5 公里内已保存定位的餐厅。",
    "restaurants.submit": "提交餐厅",
    "restaurants.searchPlaceholder": "搜索餐厅、地址、菜系或价位...",
    "restaurants.locate": "定位附近餐厅",
    "restaurants.viewAll": "查看全部",
    "restaurants.viewingNearby": "正在查看当前位置附近 {radius} 公里内餐厅",
    "restaurants.emptyTitle": "没有找到餐厅",
    "restaurants.emptyNearby": "附近暂无已保存定位的餐厅。你可以先提交一家，并使用当前位置保存定位。",
    "restaurants.emptySearch": "可以调整搜索词，或提交新的餐厅。",
    "restaurants.favorite": "收藏",
    "restaurants.unfavorite": "取消收藏",
    "restaurants.toastFavAdded": "已添加到收藏",
    "restaurants.toastFavFailed": "添加收藏失败",
    "restaurants.toastFavRemoved": "已从收藏移除",
    "restaurants.toastRemoveFavFailed": "移除收藏失败",
    "restaurants.toastNoGeo": "当前浏览器不支持定位",
    "restaurants.toastLocated": "已定位，正在筛选附近餐厅",
    "restaurants.toastLocationFailed": "定位失败，请允许浏览器位置权限后重试",

    "submitRestaurant.backTitle": "提交餐厅",
    "submitRestaurant.heading": "推荐一家好店",
    "submitRestaurant.subtitle": "填写餐厅地址、定位和评分，审核通过后会进入餐厅页面。",
    "submitRestaurant.loginRequired": "请先登录后再提交餐厅",
    "submitRestaurant.goLogin": "去登录",
    "submitRestaurant.successTitle": "提交成功",
    "submitRestaurant.successBody": "餐厅信息已经进入审核流程，管理员审核通过后会出现在餐厅页面。",
    "submitRestaurant.submitMore": "继续提交",
    "submitRestaurant.viewRestaurants": "查看餐厅",
    "submitRestaurant.name": "餐厅名称",
    "submitRestaurant.namePlaceholder": "例如：老王家炒饭",
    "submitRestaurant.address": "餐厅地址",
    "submitRestaurant.addressPlaceholder": "例如：西交利物浦大学北校区附近",
    "submitRestaurant.useLocation": "使用当前位置",
    "submitRestaurant.locationSaved": "已记录餐厅定位",
    "submitRestaurant.price": "人均消费",
    "submitRestaurant.pricePlaceholder": "例如：30-50 元/人",
    "submitRestaurant.rating": "餐厅评分",
    "submitRestaurant.starLabel": "{star} 星",
    "submitRestaurant.description": "餐厅描述",
    "submitRestaurant.descriptionPlaceholder": "简单说说这家店值得推荐的原因，比如招牌菜、口味、环境、适合什么场景...",
    "submitRestaurant.image": "餐厅图片（可选）",
    "submitRestaurant.previewAlt": "餐厅图片预览",
    "submitRestaurant.removeImage": "移除图片",
    "submitRestaurant.uploadImage": "点击上传餐厅图片",
    "submitRestaurant.uploadSupport": "支持 JPG、PNG，最大 5MB",
    "submitRestaurant.notice": "提交后会进入后台审核。评分会作为餐厅初始五星评分保存，定位信息会用于附近餐厅搜索。",
    "submitRestaurant.submitting": "提交中...",
    "submitRestaurant.toastNoGeo": "当前浏览器不支持定位",
    "submitRestaurant.toastLocated": "已定位并填入餐厅地址",
    "submitRestaurant.toastLocationPartial": "已获取定位，但地址解析失败，可以手动填写地址",
    "submitRestaurant.toastLocationFailed": "定位失败，请允许浏览器位置权限后重试",
    "submitRestaurant.toastImageTooLarge": "图片大小不能超过 5MB",
    "submitRestaurant.toastNameRequired": "请输入餐厅名称",
    "submitRestaurant.toastAddressRequired": "请输入餐厅地址",
    "submitRestaurant.toastPriceRequired": "请输入人均消费",
    "submitRestaurant.toastRatingRequired": "请给餐厅选择 1-5 星评分",
    "submitRestaurant.toastDescriptionRequired": "请输入餐厅描述",
    "submitRestaurant.toastPreview": "本地预览模式：表单校验通过，未提交到数据库",
    "submitRestaurant.toastSubmitFailed": "提交失败：{message}",
    "submitRestaurant.retryLater": "请稍后重试",

    "restaurantDetail.back": "返回餐厅列表",
    "restaurantDetail.notFound": "餐厅不存在",
    "restaurantDetail.description": "餐厅介绍",
    "restaurantDetail.noDescription": "暂无餐厅描述。",
    "restaurantDetail.address": "地址",
    "restaurantDetail.price": "人均消费",
    "restaurantDetail.locationSaved": "已记录定位",
    "restaurantDetail.locationInfoSaved": "已保存餐厅定位信息",
    "restaurantDetail.favorited": "已收藏",
    "restaurantDetail.favorite": "收藏餐厅",

    "rankings.badge": "数据库餐厅榜",
    "rankings.title": "周边餐厅排行榜",
    "rankings.subtitle": "通过当前位置搜索周边餐厅，榜单只从我们数据库里的餐厅记录生成。",
    "rankings.locate": "定位周边餐厅",
    "rankings.searchPlaceholder": "搜索餐厅、地址、菜系或价位...",
    "rankings.viewAll": "查看全部数据库餐厅",
    "rankings.restaurantPage": "餐厅页面",
    "rankings.filtered": "已使用当前位置筛选周边餐厅",
    "rankings.emptyNearbyTitle": "附近暂无可排行餐厅",
    "rankings.emptyTitle": "暂无餐厅排行数据",
    "rankings.emptyNearbyBody": "附近没有已保存定位的数据库餐厅。可以先在餐厅页提交餐厅并使用定位保存位置。",
    "rankings.emptyBody": "当前数据库里还没有可展示的餐厅记录，或餐厅还没有评分。",
    "rankings.browseRestaurants": "浏览餐厅",
    "rankings.infoTitle": "排行榜说明",
    "rankings.infoSource": "榜单数据来自数据库里的餐厅记录，不使用 mock 餐厅。",
    "rankings.infoLocation": "定位后会按照你的位置查询半径内已保存定位的餐厅。",
    "rankings.infoScore": "综合分参考餐厅评分、评分数和距离，距离越近排名会略微靠前。",
    "rankings.toastLocated": "已定位，正在生成周边餐厅榜单",

    "postDetail.back": "返回社区",
    "postDetail.notFound": "帖子不存在",
    "postDetail.comments": "评论",
    "postDetail.discussions": "{count} 条讨论",
    "postDetail.noComments": "还没有评论",
    "postDetail.placeholder": "写下你的评论...",
    "postDetail.publish": "发布",
    "postDetail.emptyComments": "暂无评论，成为第一个评论的人。",
    "postDetail.badImagesTitle": "这条旧帖的图片源已经失效",
    "postDetail.badImagesBody": "原始地址是测试占位图，远端返回 404，所以本地预览已隐藏坏图，避免继续显示破图。",
    "postDetail.enlargedAlt": "放大图片",
    "postDetail.confirmDeleteComment": "确定要删除这条评论吗？",
    "postDetail.confirmDeletePost": "确定要删除这条帖子吗？",
    "postDetail.toastCommentRequired": "请输入评论内容",
    "postDetail.toastCommentSuccess": "评论成功",
    "postDetail.toastCommentFailed": "评论失败：{message}",
    "postDetail.toastDeletedComment": "评论已删除",
    "postDetail.toastNoDeleteComment": "你没有权限删除这条评论",

    "profile.editNamePlaceholder": "输入新昵称",
    "profile.localPreviewAccount": "本地预览账号",
    "profile.noEmail": "未绑定邮箱",
    "profile.logout": "退出登录",
    "profile.posts": "发布",
    "profile.likes": "喜欢",
    "profile.followers": "粉丝",
    "profile.info": "个人信息",
    "profile.myPosts": "我的发布",
    "profile.myLikes": "我的喜欢",
    "profile.contact": "联系信息",
    "profile.email": "邮箱",
    "profile.emailReadonly": "邮箱不可修改",
    "profile.phone": "手机号",
    "profile.phonePlaceholder": "输入手机号",
    "profile.wechat": "微信号",
    "profile.wechatPlaceholder": "输入微信号",
    "profile.qq": "QQ号",
    "profile.qqPlaceholder": "输入QQ号",
    "profile.saving": "保存中...",
    "profile.saveInfo": "保存信息",
    "profile.noPosts": "还没有发布过帖子",
    "profile.goPublish": "去发布",
    "profile.noLikes": "还没有喜欢过帖子",
    "profile.goCommunity": "去社区看看",
    "profile.toastNameUpdated": "昵称已更新",
    "profile.toastUpdateFailed": "更新失败：{message}",
    "profile.toastInfoUpdated": "个人信息已更新",
    "profile.toastNameRequired": "昵称不能为空",

    "ai.title": "AI 美食助手",
    "ai.powered": "GLM-4 驱动",
    "ai.subtitle": "基于你的收藏和喜好，提供个性化美食推荐",
    "ai.welcome": "你好！👋 我是吃了吗 AI 助手，由 GLM-4 驱动。\n\n我已经了解了你在平台上的收藏和点赞记录，可以为你提供个性化的美食推荐。\n\n点击下方「📍 获取我的位置」按钮，我还能为你推荐附近的餐厅！",
    "ai.promptTaste": "根据我的口味推荐几家餐厅",
    "ai.promptNearby": "附近有什么好吃的？",
    "ai.promptHot": "平台上最近有什么热门美食？",
    "ai.promptDate": "帮我推荐适合约会的餐厅",
    "ai.getLocation": "📍 获取我的位置",
    "ai.locating": "定位中…",
    "ai.locatedShort": "已定位",
    "ai.locationShared": "位置已共享",
    "ai.locationMessageWithAddress": "已获取你的位置：{address}",
    "ai.locationMessage": "已获取你的位置",
    "ai.locationAssistantHint": "现在你可以问我「附近有什么好吃的」，我会根据你的实时位置推荐附近餐厅！",
    "ai.thinking": "AI 思考中…",
    "ai.inputNearby": "问我附近有什么好吃的…",
    "ai.inputDefault": "问我任何关于美食的问题…",
    "ai.footerLocation": "📍 正在共享位置 · AI 回复仅供参考",
    "ai.footerDefault": "AI 回复仅供参考，实际用餐体验以餐厅现场为准",
    "ai.toastNoGeo": "你的浏览器不支持定位功能",
    "ai.toastLocationSuccessWithAddress": "位置获取成功：{address}",
    "ai.toastLocationSuccess": "位置获取成功",
    "ai.toastLocationPermission": "请允许浏览器访问你的位置",
    "ai.toastLocationFailed": "无法获取位置，请稍后重试",
    "ai.toastLocationClosed": "已关闭位置共享",
    "ai.error": "抱歉，AI 助手暂时无法响应，请稍后再试。（{message}）",

    "admin.title": "管理后台",
    "admin.greeting": "Hi，{name}",
    "admin.adminFallback": "管理员",
    "admin.superAdmin": "总管",
    "admin.overview": "数据概览",
    "admin.restaurantManagement": "餐厅管理",
    "admin.userList": "用户列表",
    "admin.adminManagement": "管理员管理",
    "admin.backCommunity": "返回社区",
    "admin.totalUsers": "注册用户",
    "admin.totalPosts": "帖子总数",
    "admin.totalRestaurants": "餐厅总数",
    "admin.pendingReview": "待审核",
    "admin.quickActions": "快捷操作",
    "admin.addRestaurant": "添加餐厅",
    "admin.manageRestaurants": "管理餐厅",
    "admin.viewUsers": "查看用户",
    "admin.searchRestaurants": "搜索餐厅名称或地址...",
    "admin.noRestaurants": "还没有餐厅数据",
    "admin.addFirstRestaurant": "添加第一家餐厅",
    "admin.usersHelp": "点击右侧按钮可直接设置或撤销管理员权限。",
    "admin.nicknameMissing": "未设置昵称",
    "admin.admin": "管理员",
    "admin.superAdminFull": "总管理员",
    "admin.setAdmin": "设为管理员",
    "admin.revoke": "撤销权限",
    "admin.noUsers": "暂无用户数据",
    "admin.adminCount": "共 {count} 位管理员",
    "admin.adminHelp": "设置用户为管理员后，对方可以登录管理后台并审核餐厅。仅您可以设置或撤销管理员权限。",
    "admin.addAdmin": "添加管理员",
    "admin.addAdminHelp": "输入用户 ID 将其设为管理员（可在用户列表中查看用户 ID）",
    "admin.currentAdmins": "当前管理员列表",
    "admin.noOtherAdmins": "暂无其他管理员",
    "admin.addAdminEmptyHelp": "在上方输入用户 ID 来添加管理员",
    "admin.userIdPlaceholder": "输入用户 ID",
    "admin.setting": "设置中...",
    "admin.editRestaurant": "编辑餐厅",
    "admin.restaurantImage": "餐厅图片",
    "admin.previewAlt": "预览",
    "admin.uploadImage": "点击上传图片（最大 5MB）",
    "admin.restaurantName": "餐厅名称 *",
    "admin.restaurantNamePlaceholder": "例：太仓老街面馆",
    "admin.cuisine": "菜系",
    "admin.chooseCuisine": "选择菜系",
    "admin.priceRange": "价格区间",
    "admin.choosePrice": "选择价格",
    "admin.address": "地址",
    "admin.addressPlaceholder": "例：太仓市上海东路1800号",
    "admin.city": "城市",
    "admin.district": "区域",
    "admin.districtPlaceholder": "例：学校南门",
    "admin.phone": "电话",
    "admin.phonePlaceholder": "联系电话（选填）",
    "admin.description": "简介",
    "admin.descriptionPlaceholder": "一句话介绍这家餐厅（选填）",
    "admin.status": "状态",
    "admin.published": "已发布",
    "admin.pending": "待审核",
    "admin.rejected": "已拒绝",
    "admin.saving": "保存中...",
    "admin.saveChanges": "保存修改",
    "admin.confirmDelete": "确认删除",
    "admin.deleteWarning": "此操作不可撤销，餐厅数据将被永久删除。",
    "admin.confirmDeleteAction": "确认删除",
    "admin.toastForbidden": "无权访问管理员后台",
    "admin.toastRoleUpdated": "权限已更新",
    "admin.toastUpdateFailed": "更新失败：{message}",
    "admin.toastRestaurantAdded": "餐厅添加成功",
    "admin.toastAddFailed": "添加失败：{message}",
    "admin.toastRestaurantUpdated": "餐厅更新成功",
    "admin.toastRestaurantDeleted": "餐厅已删除",
    "admin.toastDeleteFailed": "删除失败：{message}",
    "admin.toastStatusUpdated": "状态已更新",
    "admin.toastImageTooLarge": "图片不能超过 5MB",
    "admin.toastNameRequired": "请输入餐厅名称",
    "admin.cuisineChinese": "中餐",
    "admin.cuisineWestern": "西餐",
    "admin.cuisineJapanese": "日料",
    "admin.cuisineKorean": "韩餐",
    "admin.cuisineFastFood": "快餐",
    "admin.cuisineSnacks": "小吃",
    "admin.cuisineDessert": "甜品",
    "admin.cuisineDrinks": "饮品",
    "admin.cuisineOther": "其他",
    "admin.priceCheap": "¥ 便宜（人均 < 30）",
    "admin.priceMedium": "¥¥ 中等（人均 30-80）",
    "admin.priceExpensive": "¥¥¥ 较贵（人均 > 80）",

    "notFound.title": "页面未找到",
    "notFound.body": "抱歉，您访问的页面不存在或已被移除。\n让我们带您回到首页吧。",
    "notFound.home": "返回首页",
  },
  en: {
    "nav.community": "Community",
    "nav.rankings": "Rankings",
    "nav.aiChat": "AI Chat",
    "nav.profile": "Me",
    "nav.discussion": "Posts",
    "nav.restaurants": "Restaurants",
    "nav.admin": "Admin",
    "language.label": "Language",
    "language.switch": "Switch language",

    "common.back": "Back",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.loading": "Loading",
    "common.view": "View",
    "common.viewDetails": "View Details",
    "common.submit": "Submit",
    "common.user": "User",
    "common.justNow": "Just now",
    "common.noRating": "No rating",
    "common.rating": "Rating",
    "common.reviews": "{count} ratings",
    "common.score": "Score",
    "common.perPerson": "Avg: ",
    "common.aboutKm": "About {distance} km",
    "common.unclassified": "Uncategorized",
    "common.aiRecommend": "AI Pick",
    "common.aiAsk": "Ask AI about this place",

    "home.login": "Log in",
    "home.register": "Sign up",
    "home.startNow": "Get Started",
    "home.learnMore": "Learn More",
    "home.heroTitle": "Chileoma",
    "home.heroSubtitle": "Discover food, share joy, and explore the best restaurants in the city with friends.",
    "home.loginTipTitle": "Login Tip",
    "home.loginTipBody": "Please sign in with Google, Microsoft, Facebook, or Apple. After redirecting, click the matching third-party login button directly.",
    "home.featureShareTitle": "Share Food",
    "home.featureShareBody": "Post food photos and reviews, and share your discoveries with the community.",
    "home.featureAiTitle": "AI Recommendations",
    "home.featureAiBody": "Tell AI your taste preferences and get smarter restaurant recommendations.",
    "home.featureRankTitle": "Restaurant Rankings",
    "home.featureRankBody": "Browse the most popular restaurants near your area.",
    "home.ctaTitle": "Ready to eat?",
    "home.ctaBody": "Join the Chileoma community to discover food, share joy, and explore every corner of the city with food lovers.",
    "home.registerNow": "Sign Up Now",
    "home.footer": "© 2024 Chileoma - Food sharing and restaurant recommendation platform",
    "home.errorInvalidEmail": "Registration failed: only @student.xjtlu.edu.cn email addresses are allowed. Please use your university email or a third-party account to log in again.",
    "home.errorOauthFailed": "Login failed: authentication error. Please try again later.",

    "feed.badge": "Community",
    "feed.title": "Posts",
    "feed.subtitle": "Share dining experiences, ask classmates for tips, and record good places you find.",
    "feed.publish": "New Post",
    "feed.loadMore": "Load More",
    "feed.empty": "No posts yet",
    "feed.publishFirst": "Publish the First Post",
    "feed.badImage": "The original image link for this old post is no longer available, so the broken image is hidden.",
    "feed.deleteTitle": "Delete post",
    "feed.confirmDelete": "Delete this post?",
    "feed.toastLikeFailed": "Failed to like: {message}",
    "feed.toastUnlikeFailed": "Failed to unlike: {message}",
    "feed.toastDeleted": "Post deleted",
    "feed.toastNoDeletePermission": "You do not have permission to delete this post",
    "feed.toastNotFound": "Post not found",
    "feed.toastDeleteFailed": "Delete failed: {message}",

    "publish.back": "Back to Community",
    "publish.title": "Share Your Food Story",
    "publish.titleLabel": "Title *",
    "publish.titleHelp": "(for example: the signature dish at this restaurant is amazing)",
    "publish.titlePlaceholder": "Example: signature dish, cozy environment, great value...",
    "publish.contentLabel": "Content *",
    "publish.contentHelp": "(share your dining experience)",
    "publish.contentPlaceholder": "Example: The ingredients are fresh, especially their...\nThe space is comfortable and good for friends...\nThe price is reasonable and the value is great...",
    "publish.chars": "{count}/{max} characters",
    "publish.ratingOptional": "Rating (optional)",
    "publish.uploadImages": "Upload Images (up to 9)",
    "publish.uploadCta": "Click or drag to upload images",
    "publish.uploadSupport": "Supports JPG, PNG, and WebP",
    "publish.submitting": "Publishing...",
    "publish.submit": "Publish",
    "publish.tipsTitle": "Sharing Tips",
    "publish.tipPhotos": "Clear photos make your post more attractive",
    "publish.tipDetails": "Detailed descriptions help other users understand better",
    "publish.tipRating": "Rate restaurants to help the community judge quality",
    "publish.tipRules": "Follow community rules and avoid inappropriate content",
    "publish.toastSuccess": "Published!",
    "publish.toastFailed": "Publish failed: {message}",
    "publish.toastRequired": "Please enter both title and content",

    "restaurants.title": "Discover Restaurants",
    "restaurants.subtitle": "Search by keyword or use your location to see restaurants saved within 5 km.",
    "restaurants.submit": "Submit Restaurant",
    "restaurants.searchPlaceholder": "Search restaurants, address, cuisine, or price...",
    "restaurants.locate": "Find Nearby",
    "restaurants.viewAll": "View All",
    "restaurants.viewingNearby": "Showing restaurants within {radius} km of your current location",
    "restaurants.emptyTitle": "No restaurants found",
    "restaurants.emptyNearby": "No nearby restaurants with saved location yet. Submit one and save its location first.",
    "restaurants.emptySearch": "Try another search term, or submit a new restaurant.",
    "restaurants.favorite": "Favorite",
    "restaurants.unfavorite": "Unfavorite",
    "restaurants.toastFavAdded": "Added to favorites",
    "restaurants.toastFavFailed": "Failed to add favorite",
    "restaurants.toastFavRemoved": "Removed from favorites",
    "restaurants.toastRemoveFavFailed": "Failed to remove favorite",
    "restaurants.toastNoGeo": "This browser does not support location",
    "restaurants.toastLocated": "Located. Filtering nearby restaurants",
    "restaurants.toastLocationFailed": "Location failed. Please allow browser location permission and try again",

    "submitRestaurant.backTitle": "Submit Restaurant",
    "submitRestaurant.heading": "Recommend a Good Place",
    "submitRestaurant.subtitle": "Fill in address, location, and rating. Once approved, it will appear on the restaurant page.",
    "submitRestaurant.loginRequired": "Please log in before submitting a restaurant",
    "submitRestaurant.goLogin": "Log In",
    "submitRestaurant.successTitle": "Submitted",
    "submitRestaurant.successBody": "The restaurant is now in review. It will appear after an admin approves it.",
    "submitRestaurant.submitMore": "Submit Another",
    "submitRestaurant.viewRestaurants": "View Restaurants",
    "submitRestaurant.name": "Restaurant Name",
    "submitRestaurant.namePlaceholder": "Example: Lao Wang Fried Rice",
    "submitRestaurant.address": "Restaurant Address",
    "submitRestaurant.addressPlaceholder": "Example: Near XJTLU North Campus",
    "submitRestaurant.useLocation": "Use Current Location",
    "submitRestaurant.locationSaved": "Restaurant location saved",
    "submitRestaurant.price": "Average Spend",
    "submitRestaurant.pricePlaceholder": "Example: 30-50 RMB/person",
    "submitRestaurant.rating": "Restaurant Rating",
    "submitRestaurant.starLabel": "{star} stars",
    "submitRestaurant.description": "Restaurant Description",
    "submitRestaurant.descriptionPlaceholder": "Briefly explain why this place is worth recommending: signature dishes, taste, environment, suitable occasions...",
    "submitRestaurant.image": "Restaurant Image (optional)",
    "submitRestaurant.previewAlt": "Restaurant image preview",
    "submitRestaurant.removeImage": "Remove image",
    "submitRestaurant.uploadImage": "Click to upload a restaurant image",
    "submitRestaurant.uploadSupport": "Supports JPG and PNG, max 5MB",
    "submitRestaurant.notice": "After submission, it will enter admin review. The rating is saved as the initial five-star rating, and location helps nearby restaurant search.",
    "submitRestaurant.submitting": "Submitting...",
    "submitRestaurant.toastNoGeo": "This browser does not support location",
    "submitRestaurant.toastLocated": "Located and filled restaurant address",
    "submitRestaurant.toastLocationPartial": "Location acquired, but address lookup failed. You can enter the address manually",
    "submitRestaurant.toastLocationFailed": "Location failed. Please allow browser location permission and try again",
    "submitRestaurant.toastImageTooLarge": "Image must be under 5MB",
    "submitRestaurant.toastNameRequired": "Please enter restaurant name",
    "submitRestaurant.toastAddressRequired": "Please enter restaurant address",
    "submitRestaurant.toastPriceRequired": "Please enter average spend",
    "submitRestaurant.toastRatingRequired": "Please choose a 1-5 star rating",
    "submitRestaurant.toastDescriptionRequired": "Please enter restaurant description",
    "submitRestaurant.toastPreview": "Local preview mode: form validation passed, not submitted to database",
    "submitRestaurant.toastSubmitFailed": "Submit failed: {message}",
    "submitRestaurant.retryLater": "Please try again later",

    "restaurantDetail.back": "Back to Restaurants",
    "restaurantDetail.notFound": "Restaurant not found",
    "restaurantDetail.description": "About",
    "restaurantDetail.noDescription": "No restaurant description yet.",
    "restaurantDetail.address": "Address",
    "restaurantDetail.price": "Average Spend",
    "restaurantDetail.locationSaved": "Location saved",
    "restaurantDetail.locationInfoSaved": "Restaurant location information saved",
    "restaurantDetail.favorited": "Favorited",
    "restaurantDetail.favorite": "Favorite Restaurant",

    "rankings.badge": "Database Restaurant Ranking",
    "rankings.title": "Nearby Restaurant Rankings",
    "rankings.subtitle": "Search nearby restaurants from your current location. Rankings only use restaurant records in our database.",
    "rankings.locate": "Rank Nearby",
    "rankings.searchPlaceholder": "Search restaurants, address, cuisine, or price...",
    "rankings.viewAll": "View All Database Restaurants",
    "rankings.restaurantPage": "Restaurant Page",
    "rankings.filtered": "Using your current location for nearby restaurants",
    "rankings.emptyNearbyTitle": "No nearby restaurants to rank",
    "rankings.emptyTitle": "No ranking data yet",
    "rankings.emptyNearbyBody": "No nearby database restaurants with saved location. You can submit one and save its location first.",
    "rankings.emptyBody": "There are no displayable restaurant records yet, or the restaurants have no ratings.",
    "rankings.browseRestaurants": "Browse Restaurants",
    "rankings.infoTitle": "How Rankings Work",
    "rankings.infoSource": "Ranking data comes from restaurant records in the database, not mock data.",
    "rankings.infoLocation": "After locating, the list searches restaurants with saved locations within the selected radius.",
    "rankings.infoScore": "Score considers rating, rating count, and distance. Nearby restaurants get a small boost.",
    "rankings.toastLocated": "Located. Generating nearby restaurant rankings",

    "postDetail.back": "Back to Community",
    "postDetail.notFound": "Post not found",
    "postDetail.comments": "Comments",
    "postDetail.discussions": "{count} discussions",
    "postDetail.noComments": "No comments yet",
    "postDetail.placeholder": "Write a comment...",
    "postDetail.publish": "Post",
    "postDetail.emptyComments": "No comments yet. Be the first to comment.",
    "postDetail.badImagesTitle": "The image source for this old post is unavailable",
    "postDetail.badImagesBody": "The original address was a test placeholder and returns 404, so broken images are hidden in local preview.",
    "postDetail.enlargedAlt": "Enlarged image",
    "postDetail.confirmDeleteComment": "Delete this comment?",
    "postDetail.confirmDeletePost": "Delete this post?",
    "postDetail.toastCommentRequired": "Please enter comment content",
    "postDetail.toastCommentSuccess": "Comment posted",
    "postDetail.toastCommentFailed": "Comment failed: {message}",
    "postDetail.toastDeletedComment": "Comment deleted",
    "postDetail.toastNoDeleteComment": "You do not have permission to delete this comment",

    "profile.editNamePlaceholder": "Enter a new nickname",
    "profile.localPreviewAccount": "Local preview account",
    "profile.noEmail": "No email linked",
    "profile.logout": "Log Out",
    "profile.posts": "Posts",
    "profile.likes": "Likes",
    "profile.followers": "Followers",
    "profile.info": "Profile",
    "profile.myPosts": "My Posts",
    "profile.myLikes": "My Likes",
    "profile.contact": "Contact Info",
    "profile.email": "Email",
    "profile.emailReadonly": "Email cannot be changed",
    "profile.phone": "Phone",
    "profile.phonePlaceholder": "Enter phone number",
    "profile.wechat": "WeChat ID",
    "profile.wechatPlaceholder": "Enter WeChat ID",
    "profile.qq": "QQ ID",
    "profile.qqPlaceholder": "Enter QQ ID",
    "profile.saving": "Saving...",
    "profile.saveInfo": "Save Info",
    "profile.noPosts": "You have not posted yet",
    "profile.goPublish": "Create a Post",
    "profile.noLikes": "You have not liked any posts yet",
    "profile.goCommunity": "Browse Community",
    "profile.toastNameUpdated": "Nickname updated",
    "profile.toastUpdateFailed": "Update failed: {message}",
    "profile.toastInfoUpdated": "Profile updated",
    "profile.toastNameRequired": "Nickname cannot be empty",

    "ai.title": "AI Food Assistant",
    "ai.powered": "Powered by GLM-4",
    "ai.subtitle": "Personalized food recommendations based on your favorites and preferences",
    "ai.welcome": "Hi! 👋 I am the Chileoma AI assistant, powered by GLM-4.\n\nI can use your favorites and likes on the platform to offer personalized food recommendations.\n\nClick the “📍 Get my location” button below and I can recommend nearby restaurants too!",
    "ai.promptTaste": "Recommend restaurants based on my taste",
    "ai.promptNearby": "What is good to eat nearby?",
    "ai.promptHot": "What food is popular on the platform lately?",
    "ai.promptDate": "Recommend restaurants for a date",
    "ai.getLocation": "📍 Get my location",
    "ai.locating": "Locating…",
    "ai.locatedShort": "Located",
    "ai.locationShared": "Location shared",
    "ai.locationMessageWithAddress": "Got your location: {address}",
    "ai.locationMessage": "Got your location",
    "ai.locationAssistantHint": "Now you can ask “what is good nearby?” and I will recommend restaurants based on your real-time location.",
    "ai.thinking": "AI is thinking…",
    "ai.inputNearby": "Ask what is good nearby…",
    "ai.inputDefault": "Ask me anything about food…",
    "ai.footerLocation": "📍 Sharing location · AI replies are for reference only",
    "ai.footerDefault": "AI replies are for reference only. Actual dining experience depends on the restaurant.",
    "ai.toastNoGeo": "Your browser does not support location",
    "ai.toastLocationSuccessWithAddress": "Location acquired: {address}",
    "ai.toastLocationSuccess": "Location acquired",
    "ai.toastLocationPermission": "Please allow browser location access",
    "ai.toastLocationFailed": "Unable to get location. Please try again later",
    "ai.toastLocationClosed": "Location sharing turned off",
    "ai.error": "Sorry, the AI assistant is temporarily unavailable. Please try again later. ({message})",

    "admin.title": "Admin",
    "admin.greeting": "Hi, {name}",
    "admin.adminFallback": "Admin",
    "admin.superAdmin": "Owner",
    "admin.overview": "Overview",
    "admin.restaurantManagement": "Restaurants",
    "admin.userList": "Users",
    "admin.adminManagement": "Admins",
    "admin.backCommunity": "Back to Community",
    "admin.totalUsers": "Users",
    "admin.totalPosts": "Posts",
    "admin.totalRestaurants": "Restaurants",
    "admin.pendingReview": "Pending",
    "admin.quickActions": "Quick Actions",
    "admin.addRestaurant": "Add Restaurant",
    "admin.manageRestaurants": "Manage Restaurants",
    "admin.viewUsers": "View Users",
    "admin.searchRestaurants": "Search restaurant name or address...",
    "admin.noRestaurants": "No restaurant data yet",
    "admin.addFirstRestaurant": "Add the First Restaurant",
    "admin.usersHelp": "Use the actions on the right to grant or revoke admin access.",
    "admin.nicknameMissing": "Nickname not set",
    "admin.admin": "Admin",
    "admin.superAdminFull": "Super Admin",
    "admin.setAdmin": "Set as Admin",
    "admin.revoke": "Revoke",
    "admin.noUsers": "No user data",
    "admin.adminCount": "{count} admins",
    "admin.adminHelp": "After a user becomes an admin, they can log in to the admin panel and review restaurants. Only you can grant or revoke admin access.",
    "admin.addAdmin": "Add Admin",
    "admin.addAdminHelp": "Enter a user ID to set them as admin. You can find user IDs in the user list.",
    "admin.currentAdmins": "Current Admins",
    "admin.noOtherAdmins": "No other admins",
    "admin.addAdminEmptyHelp": "Enter a user ID above to add an admin",
    "admin.userIdPlaceholder": "Enter user ID",
    "admin.setting": "Setting...",
    "admin.editRestaurant": "Edit Restaurant",
    "admin.restaurantImage": "Restaurant Image",
    "admin.previewAlt": "Preview",
    "admin.uploadImage": "Click to upload image (max 5MB)",
    "admin.restaurantName": "Restaurant Name *",
    "admin.restaurantNamePlaceholder": "Example: Taicang Old Street Noodles",
    "admin.cuisine": "Cuisine",
    "admin.chooseCuisine": "Choose cuisine",
    "admin.priceRange": "Price Range",
    "admin.choosePrice": "Choose price",
    "admin.address": "Address",
    "admin.addressPlaceholder": "Example: 1800 Shanghai East Road, Taicang",
    "admin.city": "City",
    "admin.district": "District",
    "admin.districtPlaceholder": "Example: South Gate",
    "admin.phone": "Phone",
    "admin.phonePlaceholder": "Contact phone (optional)",
    "admin.description": "Description",
    "admin.descriptionPlaceholder": "One-sentence restaurant intro (optional)",
    "admin.status": "Status",
    "admin.published": "Published",
    "admin.pending": "Pending",
    "admin.rejected": "Rejected",
    "admin.saving": "Saving...",
    "admin.saveChanges": "Save Changes",
    "admin.confirmDelete": "Confirm Delete",
    "admin.deleteWarning": "This cannot be undone. The restaurant data will be permanently deleted.",
    "admin.confirmDeleteAction": "Delete",
    "admin.toastForbidden": "No permission to access admin panel",
    "admin.toastRoleUpdated": "Permission updated",
    "admin.toastUpdateFailed": "Update failed: {message}",
    "admin.toastRestaurantAdded": "Restaurant added",
    "admin.toastAddFailed": "Add failed: {message}",
    "admin.toastRestaurantUpdated": "Restaurant updated",
    "admin.toastRestaurantDeleted": "Restaurant deleted",
    "admin.toastDeleteFailed": "Delete failed: {message}",
    "admin.toastStatusUpdated": "Status updated",
    "admin.toastImageTooLarge": "Image must be under 5MB",
    "admin.toastNameRequired": "Please enter restaurant name",
    "admin.cuisineChinese": "Chinese",
    "admin.cuisineWestern": "Western",
    "admin.cuisineJapanese": "Japanese",
    "admin.cuisineKorean": "Korean",
    "admin.cuisineFastFood": "Fast Food",
    "admin.cuisineSnacks": "Snacks",
    "admin.cuisineDessert": "Dessert",
    "admin.cuisineDrinks": "Drinks",
    "admin.cuisineOther": "Other",
    "admin.priceCheap": "¥ Cheap (avg < 30)",
    "admin.priceMedium": "¥¥ Medium (avg 30-80)",
    "admin.priceExpensive": "¥¥¥ Expensive (avg > 80)",

    "notFound.title": "Page Not Found",
    "notFound.body": "Sorry, the page you visited does not exist or has been removed.\nLet us take you back home.",
    "notFound.home": "Back Home",
  },
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, params?: TranslationParams) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

const readInitialLanguage = (): Language => {
  if (typeof window === "undefined") return "zh";
  return window.localStorage.getItem(STORAGE_KEY) === "en" ? "en" : "zh";
};

const interpolate = (text: string, params?: TranslationParams) => {
  if (!params) return text;
  return Object.entries(params).reduce(
    (current, [key, value]) =>
      current.replaceAll(`{${key}}`, String(value)),
    text
  );
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(readInitialLanguage);

  const setLanguage = useCallback((nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    window.localStorage.setItem(STORAGE_KEY, nextLanguage);
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguageState((current) => {
      const nextLanguage = current === "zh" ? "en" : "zh";
      window.localStorage.setItem(STORAGE_KEY, nextLanguage);
      return nextLanguage;
    });
  }, []);

  useEffect(() => {
    document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
  }, [language]);

  const t = useCallback(
    (key: string, params?: TranslationParams) => {
      const text = translations[language][key] ?? translations.zh[key] ?? key;
      return interpolate(text, params);
    },
    [language]
  );

  const value = useMemo(
    () => ({ language, setLanguage, toggleLanguage, t }),
    [language, setLanguage, toggleLanguage, t]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return value;
}
